### PR TITLE
Fix version equals

### LINKED ISSUE #175: Version equals is probably wrong
Write some tests lol

### PR DESCRIPTION
**Pull request by braxtonhall**
resolves #175

### CODE REVIEW

File: extension/ts/content/extensions/version/version.ts [hunk 1]
```diff
@@ -4,34 +4,35 @@ interface Version {
...
 };
 
-const versionLessThan = versionCompare((a, b) => a < b);
+const versionEQ = (a: Version, b: Version) => ["major", "minor", "revision"].every((key) => a[key] === b[key]);
 
-const versionEquals = versionCompare((a, b) => a === b);
+const versionLTE = (a: Version, b: Version) => versionLT(a, b) || versionEQ(a, b);
+const versionGT = (a: Version, b: Version) => !versionLTE(a, b);
+const versionGTE = (a: Version, b: Version) => !versionLT(a, b);
+const versionNEQ = (a: Version, b: Version) => !versionEQ(a, b);
```
Comment (adirar111) [inline extension/ts/content/extensions/version/version.ts:30]: it's giving 310 comparator ebnf

**Review by adirar111 — APPROVED** [review]
noiiiiiiiiice
