### PR TITLE
Make logo show up everywhere

### LINKED ISSUE #27: VBL Logo doesn't work on many pages
Groups/Talk/Local/More/Zeitgeist

The corresponding element ids are different on that page for some reason.

Probably doesn't matter as it still works on the pages needed for cataloguing.

### PR DESCRIPTION
**Pull request by braxtonhall**
resolves #27 

draft for now because i wanna move a lot of these styles into custom sass that we import

I believe it'll work faster that way too

### CODE REVIEW

File: src/ts/content/entities/bookForm/data/uniqueData/physicalDescription/index.ts [hunk 1]
```diff
@@ -15,7 +15,7 @@ const calculateRow = (element: Element): number => {
 	const fieldSet = element.closest("fieldset");
 	const siblings = Array.from(fieldSet.parentElement.children);
 	const rows = siblings.filter(isPhysicalDescriptionRow);
-	return rows.findIndex((row) => row === fieldSet);
+	return rows.indexOf(fieldSet);
```
Comment (adirar111) [inline src/ts/content/entities/bookForm/data/uniqueData/physicalDescription/index.ts:18]: mmm

**Review by adirar111 — APPROVED** [review]
noice
