### PR TITLE
Fix wrong case for people when saving tags

### LINKED ISSUE #150: If people case a tag incorrectly, just fix it for them automatically
I think for now, we just leave it as is, and then in the future we automatically fix people's bad casing

_Originally posted by @braxtonhall in https://github.com/braxtonhall/library-thing/pull/121#discussion_r1014890250_

### PR DESCRIPTION
**Pull request by braxtonhall**
resolves #150

### CODE REVIEW

File: extension/ts/content/adapters/tags/parseTags.ts [hunk 1]
```diff
@@ -14,7 +14,7 @@ const parseRows = ({rows, fromRow, depth, tree, parent}: ParserOptions): number
 		const tag = rows[row][depth];
 		if (tag) {
 			const node = {tag, parent};
-			tree.set(tag, node);
+			tree.set(tag.toLowerCase(), node);
```
Comment (adirar111) [inline extension/ts/content/adapters/tags/parseTags.ts:17]: are the keys all the lowercase tags and the values the actual tags from the sheet (with correct casing)?

**Review by adirar111 — APPROVED** [review]
wooo

File: extension/ts/content/adapters/tags/parseTags.ts (hunk 1 above)
Comment (braxtonhall) [reply extension/ts/content/adapters/tags/parseTags.ts:17]: yeah i should probably write that somewhere
