### PR TITLE
Clear Modals by clicking them instead of deleting all overlays

### LINKED ISSUE #248: `clearOverlays` oddities
This doesn't currently happen but it could

If you create an overlay either in the modal, and then clearOverlays, the onCancel will never get called, which is often needed to resolve the client's promise. So the modal needs to automatically call onCancel if clearOverlays is called

Next if you call clearOverlays during a loader overlaid action, it will attempt to remove something from the DOM that is not there anymore

### LINKED ISSUE #250: Repair enforcement
I can't believe I've done this

But as far as I can tell right now, it's broken? Like you can close the modal. I think it's a clearOverlays race condition.

### PR DESCRIPTION
**Pull request by braxtonhall**
1. It didn't make much sense to be clearing all overlays, when that would clear loaders as well. So instead we clear specifically modals. We just click them, and let the default remove implementation deal with it. resolves #248 
2. Now in my local testing, the enforcement is working again? Only I _swear_ it was working before I uploaded it to the web store, so maybe the race condition is environment dependent???? Anyway, resolves #250 
   - Edit: no just checked out main and it's still borked locally. No clue when I slipped the regression in
   - Edit 2: did a proper build and the bug is NOT fixed. seems like it works on a `yarn watch` but doesn't on a `yarn build`. deffo a race condition
   - Edit 3: No it turns out when I did a yarn build and then reloaded the extension in the browser, it was somehow using the webstore one? I removed the extension completely and then reloaded it, and everything is working as intended

### CODE REVIEW

File: src/ts/common/ui/modal.ts [hunk 1]
```diff
@@ -96,12 +98,18 @@ const addOnClick = (element: HTMLElement, exit: () => void, onClick?: () => Prom
 	element.addEventListener("click", () => callback().finally(exit));
 };
 
+const dismissModals = (): void => activeOverlays.forEach((modal) => modal.dispatchEvent(new Event("click")));
```
Comment (adirar111) [inline src/ts/common/ui/modal.ts:101]: ahhhhh cool!

**Review by adirar111 — APPROVED** [review]
PR desc was a roller coaster of emotions but i'm glad it works lol
